= Pancakes de papa

* Porciones: 5
* Tiempo de preparación: 10 minutos
* Tiempo de cocción: 20 minutos

== Ingredientes

* 400 g de puré de papas
* 100 g de mozzarella rallada
* 100 g de queso crema
* 2 huevos
* 2 cucharadas de harina leudante o maicena
* 1 puñado de perejil picado
* 2 ramas de cebolla de verdeo picadas
* Sal y pimienta, a gusto

== Preparación

. Mezclar el puré con el perejil, cebolla de verdeo, sal, condimentos y harina.
. Agregar el queso crema y huevos, mezclar hasta obtener una masa tierna pero consistente.
Incorporar el queso rallado y mezclar.
. Con las manos aceitadas tomar porciones chicas de la mezcla, dar forma de bollo y después aplastar.
. Colocar y cocinar en sartén caliente con un poco de aceite.
. Cocinar a fuego mínimo hasta dorar muy bien ambas partes.
Antes de dar vuelta, asegurarse de que ya se formó una costra crocante y firme, así es más fácil dar vuelta con espátula.

[TIP]
====
* Utilizar queso crema light y reduce la cantidad de queso rallado para disminuir las calorías.
* Añadir una pizca de ajo en polvo o cebolla en polvo a la mezcla para intensificar el sabor.
====

====
Autora: *Patricia Zacarías* @recetasdepato footnote:[https://www.clarin.com/recetas/entradas/pancake-papa_7_fiZszjdr7.html[clarin.com]]


====
