site:
  title: Recetas
  url: https://recetas.com
  start_page: ROOT::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: .
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
